language: objective-c

env:
 global:
  - EnableNuGetPackageRestore=true 
 matrix:
  - MONO_VERSION="3.8.0"

before_install:
 - wget "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
 - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /

script:
 - cd src && xbuild && cd ..
 - .ci/nunit.sh src/prismic.tests/bin/Debug/prismic.tests.dll
 - .ci/nunit.sh src/prismic.csharp.tests/bin/Debug/prismic.csharp.tests.dll

